<a href="https://colab.research.google.com/github/FathimaNazarudeen/Advanced-Computing-Lab/blob/main/Experiment%204/decision_tree2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data=pd.read_csv("/content/bank.csv")

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
z=["job","marital","education","default","housing","loan","contact","month","poutcome"]
data[z]=data[z].apply(le.fit_transform)
data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,0,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3,yes
1,56,0,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3,yes
2,41,9,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3,yes
3,55,7,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3,yes
4,54,0,1,2,0,184,0,0,2,5,8,673,2,-1,0,3,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,1,2,0,0,1,1,0,0,20,0,257,1,-1,0,3,no
11158,39,7,1,1,0,733,0,0,2,16,6,83,4,-1,0,3,no
11159,32,9,2,1,0,29,0,0,0,19,1,156,2,-1,0,3,no
11160,43,9,1,1,0,0,0,1,0,8,8,9,2,172,5,0,no
11161,34,9,1,1,0,0,0,0,0,9,5,628,1,-1,0,3,no

In [4]:
x=data[["job","marital","education","default","housing","loan","contact","month","poutcome"]]
y=data["deposit"]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9,random_state=0)

In [6]:
from sklearn.tree import DecisionTreeClassifier
ml = DecisionTreeClassifier(random_state=0,max_depth=2,criterion='entropy')

In [7]:
model=ml.fit(x_train,y_train)

In [8]:
res=model.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score

In [10]:
accuracy_1=accuracy_score(y_test,res)
print("Decision tree :",accuracy_1*100)

Decision tree : 57.475380483437775

In [11]:
from sklearn import tree
import graphviz
dot_data=tree.export_graphviz(ml,filled=True)
graph = graphviz.Source(dot_data)
graph