<a href="https://colab.research.google.com/github/FathimaNazarudeen/Advanced-Computing-Lab/blob/main/Experiment%204/decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
data=pd.read_csv("/content/bank.csv")

In [11]:
df=pd.DataFrame(data)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df=df.apply(le.fit_transform)
x=df[["job","marital","education","default","housing","loan","contact","month","poutcome"]]
y=df["deposit"]
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,41,0,1,1,0,2288,1,0,2,4,8,1021,0,0,0,3,1
1,38,0,1,1,0,469,0,0,2,4,8,1283,0,0,0,3,1
2,23,9,1,1,0,1618,1,0,2,4,8,1246,0,0,0,3,1
3,37,7,1,1,0,2356,1,0,2,4,8,577,0,0,0,3,1
4,36,0,1,2,0,608,0,0,2,4,8,671,1,0,0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,15,1,2,0,0,425,1,0,0,19,0,255,0,0,0,3,0
11158,21,7,1,1,0,1149,0,0,2,15,6,81,3,0,0,3,0
11159,14,9,2,1,0,453,0,0,0,18,1,154,1,0,0,3,0
11160,25,9,1,1,0,424,0,1,0,7,8,7,1,155,5,0,0
11161,16,9,1,1,0,424,0,0,0,8,5,626,0,0,0,3,0

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9,random_state=0)

In [13]:
from sklearn.tree import DecisionTreeClassifier
ml = DecisionTreeClassifier(random_state=0,max_depth=2)

In [14]:
model=ml.fit(x_train,y_train)

In [15]:
res=model.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_1=accuracy_score(y_test,res)
print("Decision tree :",accuracy_1*100)

Decision tree : 62.1307072515667

In [18]:
from sklearn import tree
import graphviz
dot_data=tree.export_graphviz(ml,filled=True)
graph = graphviz.Source(dot_data)
graph